### ISSUE TITLE
Travis CI Builds Failing - AutoModuleShareDirs

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1805]
Looks like the package `Dist::Zilla::Plugin::AutoModuleShareDirs` has been removed from CPAN, this results in the `dzil` command failing as it cannot fetch the package. 

`dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --notest --quiet --mirror http://www.cpan.org/ --mirror http://duckpan.org`

`Failed to fetch distribution Dist-Zilla-Plugin-AutoModuleShareDirs-0.001`

This also effects Goodies

@moollaza

**Comment by moollaza** [comment]
@MrChrisW Thanks, investigating...

**Comment by moollaza** [comment]
Should be fixed....will re-run builds.

**Comment by MrChrisW** [comment]
@moollaza Not fixed yet as the package `AutoModuleShareDirs` still cannot be fetched.

**Comment by MrChrisW** [comment]
Resolved.
